#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

# Read in the passwords....
. /root/.digitalocean_passwords

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's Custom Bun.js Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

Use these SFTP credentials to upload files with FileZilla/WinSCP/rsync:
    Host: ${myip}
    User: ${BUN_USER}
    Pass: ${BUN_USER_PASSWORD}

In a web browser, you can view the public web site at: http://$myip

On the server:
  * The public web site is served from /var/www/html
  * The passwords and keys are saved in /root/.digitalocean_passwords

For help and more information, visit https://github.com/acfata/packer-digitalocean-bun

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f "${0}")
EOF
